-- Initial Schema

CREATE TABLE articles (
    id BIGINT PRIMARY KEY,
    author TEXT NOT NULL,
    published_at TIMESTAMPTZ NOT NULL,
    reactions INT DEFAULT 0,
    comments INT DEFAULT 0,
    tags TEXT[] DEFAULT '{}',
    canonical_url TEXT,
    title TEXT,
    score INT,
    attention_level TEXT,
    explanations TEXT[],
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE users (
    username TEXT PRIMARY KEY,
    joined_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE commenters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    username TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(article_id, username)
);

-- Indices for faster lookups
CREATE INDEX idx_articles_author ON articles(author);
CREATE INDEX idx_commenters_article_id ON commenters(article_id);
CREATE INDEX idx_commenters_username ON commenters(username);

-- Enable Row Level Security (RLS)
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE commenters ENABLE ROW LEVEL SECURITY;
